MY_PRIVATE_IP: 127.0.0.1
MY_PUBLIC_IP: "{{ansible_default_ipv4.address}}"
RABBIT_PASS: rabbitmqpw
MYSQL_ROOTPASS: mysqlpw
KEYSTONE_DBUSER: dbkeystoneu
KEYSTONE_DBPASS: dbkeystonepw
ADMIN_TOKEN: ADMIN
REGION_NAME: RegionOne
SERVICE_PROJECT: service
ADMIN_PROJECT: admin
DEMO_PROJECT: demo
DEMO_USER: user
DEMO_PASS: upassword
ADMIN_USER: admin
ADMIN_PASS: apassword
ADMIN_ROLE_NAME: admin
DEMO_ROLE_NAME: user
GLANCE_DBUSER: dbglanceu
GLANCE_DBPASS: dbglancepw
GLANCE_USER: glance
GLANCE_PASS: glancepw
NOVA_DBUSER: dbnovau
NOVA_DBPASS: dbnovapw
NOVA_USER: nova
NOVA_PASS: novapw
NEUTRON_DBUSER: dbneutronu
NEUTRON_DBPASS: dbneutronpw
NEUTRON_USER: neutron
NEUTRON_PASS: neutronpw
METADATA_SECRET: mysecret
PRIV_SUBNET: 192.168.1.0/24
EXT_INTERFACE: eth0
CINDER_DBUSER: dbcinderu
CINDER_DBPASS: dbcinderpw
CINDER_USER: cinder
CINDER_PASS: cinderpw
PVNAME: /dev/xvdb1
VGNAME: cinder-volumes
