- name: Create Neutron DB
  mysql_db: name=neutron state=present

- name: Create Neutron DB user/pass
  mysql_user: name={{ NEUTRON_DBUSER }} password={{ NEUTRON_DBPASS }} priv=neutron.*:ALL state=present

# There is bug on v3 api call, then I'm using the this flags to authenticate instead of the ones in admin-openrc.sh
- name: Create neutron user
  command: openstack --os-auth-url http://{{MY_PRIVATE_IP}}:35357/v2.0 --os-tenant-name {{ADMIN_PROJECT}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} user create --password {{NEUTRON_PASS}} {{NEUTRON_USER}} 

- name: Add neutron user into admin role
  command: openstack --os-auth-url http://{{MY_PRIVATE_IP}}:35357/v2.0 --os-tenant-name {{ADMIN_PROJECT}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} role add --project {{SERVICE_PROJECT}} --user {{NEUTRON_USER}} {{ADMIN_ROLE_NAME}} 

- name: Create the neutron service entity
  command: openstack --os-auth-url http://{{MY_PRIVATE_IP}}:35357/v2.0  --os-tenant-name {{ADMIN_PROJECT}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} service create --name neutron --description "Openstack Networking" network

- name: Create the Compute service API endpoints
  command: openstack --os-auth-url http://{{MY_PRIVATE_IP}}:35357/v2.0  --os-tenant-name {{ADMIN_PROJECT}} --os-username {{ADMIN_USER}} --os-password {{ADMIN_PASS}} endpoint create --publicurl http://{{MY_PUBLIC_IP}:9696 --internalurl http://{{MY_PRIVATE_IP}}:9696 --adminurl http://{{MY_PRIVATE_IP}}:9696 --region {{REGION_NAME}} network

- name: Installing Neutron components
  action: yum pkg={{item}} state=installed
  with_items:
      - openstack-neutron
      - openstack-neutron-ml2
      - python-neutronclient

- name: Adding the neutron settings
  template: src=neutron.conf.j2 dest=/etc/neutron/neutron.conf

- name: Adding the neutron ML2 plug-in settings
  template: src=ml2_conf.ini.j2 dest= /etc/neutron/plugins/ml2/ml2_conf.ini

- name: Create symlink pointing to the ML2 plug-in configuration file
  shell: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini

- name: Populate the network service database
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

- name: Start the Compute services
  service: name={{item}} state=restarted
  with_items:
      - openstack-nova-api.service
      - openstack-nova-scheduler.service
      - openstack-nova-conductor.service
        
- name: Start the Networking service and configure it to start at boot time.
  service: name=neutron-server.service state=restarted enabled=yes
